// Cinematic recaps: staged scenes inside the 3D city at the moments that matter.
// The clock stops, letterbox bars slide in, the palette desaturates, the camera dollies to
// the block that matters, the title types itself, and each narration line triggers something
// on the ground: a crowd converging on city hall, trucks leaving, a lesson cracking.
// Every line is generated by template from the run's cause-tagged events. Nothing is invented.
import * as THREE from "three";

const NAMES = { caesar: "Caesar", bureaucrat: "The Bureaucrat", reformer: "The Reformer", populist: "The Populist", reformer_shuffled: "The Reformer (shuffled)" };
const nice = m => NAMES[m] || m;
const LEVER_WORDS = { build_factory: "a factory", build_park: "a park", build_housing: "new housing", fund_transit: "a transit line", fund_services: "services funding", subsidize_business: "business subsidies", borrow: "a loan", set_tax: "a tax change", demolish: "a demolition", buy_land: "a land purchase" };

// ---------------------------------------------------------------------------
// 1. Planning: which years get a recap, and what kind. At most `cap` per term.
// ---------------------------------------------------------------------------
export function planRecaps(ep, cap = 4) {
  const H = ep.history, cands = [];
  const stateAt = y => y <= 0 ? H[0].state_before : H[y - 1].state;
  for (let y = 1; y <= H.length; y++) {
    const rec = H[y - 1], s = rec.state, p = stateAt(y - 1);
    const dh = s.happiness - p.happiness, dpop = (s.population - p.population) / Math.max(p.population, 1);
    const loan = rec.events.find(e => e.cause_action === "borrow" && e.variable === "debt" && e.cause_year === y);
    const landed = rec.events.filter(e => e.cause_action !== "economy" && e.cause_year < y && ["factories", "parks", "housing", "transit"].includes(e.variable));
    const factoryLanded = landed.find(e => e.variable === "factories");
    if (rec.ended && rec.ended !== "horizon") cands.push({ year: y, type: rec.ended === "revolt" ? "revolt" : rec.ended === "bankruptcy" ? "bankruptcy" : "exodus", priority: 100 });
    if (dh <= -8) cands.push({ year: y, type: "revolt", priority: 60 + Math.abs(dh) });
    if (dpop <= -0.07) cands.push({ year: y, type: "exodus", priority: 55 + Math.abs(dpop) * 100 });
    if (p.treasury >= 0 && s.treasury < 0 && s.debt > 1500) cands.push({ year: y, type: "bankruptcy", priority: 50 });
    if (loan && loan.delta >= 1000) cands.push({ year: y, type: "loan", priority: 35 + loan.delta / 200, loan });
    if (factoryLanded) cands.push({ year: y, type: "landing", priority: 30, landed: factoryLanded });
    else if (landed.length) cands.push({ year: y, type: "landing", priority: 22, landed: landed[0] });
    if (s.unemployment >= 0.2 && (p.unemployment || 0) < 0.2) cands.push({ year: y, type: "layoffs", priority: 45 });
    const refused = rec.ignored.find(i => /lots/.test(i.why)); if (refused) cands.push({ year: y, type: "landfull", priority: 28, refused });
  }
  // the end of the term always gets one: a failed lesson beats everything; an early ending is staged as itself
  const last = H.length, endRec = H[last - 1];
  const failed = (ep.memory_diff?.checked || []).filter(v => v.verdict === "failed");
  const endType = failed.length ? "lesson_failed" : (endRec.ended && endRec.ended !== "horizon") ? (endRec.ended === "revolt" ? "revolt" : endRec.ended === "bankruptcy" ? "bankruptcy" : "exodus") : "term_end";
  const finale = { year: last, type: endType, priority: 200, failed, isEnd: true };
  // fixed beats at 5/10/15 if nothing else near them
  for (const y of [5, 10, 15]) if (y < last - 1 && !cands.some(c => Math.abs(c.year - y) <= 2 && c.priority >= 30)) cands.push({ year: y, type: "quiet", priority: 10 });
  // pick: the finale, then best by priority; one recap per type; at least 3 years apart
  const chosen = [finale];
  const others = cands.filter(c => c.year < last - 1).sort((a, b) => b.priority - a.priority);
  for (const c of others) {
    if (chosen.length >= cap) break;
    if (chosen.some(x => x.type === c.type)) continue;
    if (chosen.some(x => Math.abs(x.year - c.year) < 3)) continue;
    chosen.push(c);
  }
  chosen.sort((a, b) => a.year - b.year);
  return chosen.map(c => ({ ...c, ...linesFor(ep, c) }));
}

function linesFor(ep, c) {
  const H = ep.history, rec = H[c.year - 1], s = rec.state, p = c.year >= 2 ? H[c.year - 2].state : H[0].state_before, m = nice(ep.mayor);
  const acts = rec.actions.map(a => `${LEVER_WORDS[a.name] || a.name}`).join(", ") || "nothing";
  const L = [];
  let title = `Year ${c.year}`;
  switch (c.type) {
    case "revolt":
      title = rec.ended === "revolt" ? "The people have had enough" : "Discontent in the streets";
      L.push(`Happiness fell from ${p.happiness} to ${s.happiness} this year.`);
      L.push(`${m} decided: ${acts}.`);
      if (s.tax_rate > 0.25) L.push(`Taxes stand at ${Math.round(s.tax_rate * 100)}%. Services at ${s.services} of 100.`);
      if (s.pollution > 40) L.push(`The air is at ${s.pollution}. Children are coughing.`);
      L.push(rec.ended === "revolt" ? `After three years below the line, the city rises. The term ends here.` : `They gather outside city hall.`);
      break;
    case "exodus":
      title = rec.ended === "depopulation" ? "A city empties" : "People are leaving";
      L.push(`Population ${p.population} → ${s.population}. ${Math.round((p.population - s.population))} people left this year.`);
      L.push(`Unemployment ${Math.round((s.unemployment || 0) * 100)}%, pollution ${s.pollution}, happiness ${s.happiness}.`);
      L.push(`${m} decided: ${acts}.`);
      L.push(`The trucks line up on the avenue.`);
      break;
    case "bankruptcy":
      title = rec.ended === "bankruptcy" ? "Bankrupt" : "The money runs out";
      L.push(`The treasury is ${s.treasury}. Debt is ${s.debt}.`);
      L.push(`Interest alone costs about ${Math.round(s.debt * 0.08)} a year, forever.`);
      L.push(`${m} decided: ${acts}.`);
      L.push(rec.ended === "bankruptcy" ? `The lights go out. The term ends here.` : `The lights start going out.`);
      break;
    case "loan":
      title = "A loan";
      L.push(`${m} borrows ${Math.round(c.loan.delta)}.`);
      L.push(`Debt is now ${s.debt}. Interest of about ${Math.round(s.debt * 0.08)} a year follows.`);
      L.push(`The term ends in year 20. The interest does not.`);
      break;
    case "landing":
      title = c.landed.variable === "factories" ? "A factory opens" : c.landed.variable === "parks" ? "A park opens" : c.landed.variable === "housing" ? "New housing" : "A transit line opens";
      L.push(`${m} ordered ${LEVER_WORDS[c.landed.cause_action] || c.landed.cause_action} in year ${c.landed.cause_year}.`);
      L.push(`It lands now: ${c.landed.variable} ${c.landed.delta > 0 ? "+" : ""}${Math.round(c.landed.delta)}${c.landed.note ? ` (${c.landed.note})` : ""}.`);
      if (c.landed.variable === "factories") L.push(`+${Math.round(150 * c.landed.delta)} jobs. And smoke, every year from now on.`);
      break;
    case "layoffs":
      title = "Out of work";
      L.push(`Unemployment crosses 20%: ${s.jobs} jobs for ${Math.round(s.population * 0.6)} workers.`);
      L.push(`${m} decided: ${acts}.`);
      L.push(`Workers stand outside the gates.`);
      break;
    case "landfull":
      title = "Out of land";
      L.push(`A build was refused: ${c.refused.why}.`);
      L.push(`${s.factories} factories, ${s.parks} parks, ${s.housing} homes. The city is full.`);
      break;
    case "lesson_failed":
      title = `${m} finds a lesson wrong`;
      for (const f of c.failed.slice(0, 2)) { L.push(`“${f.rule}”`); L.push(`Checked against this term: ${f.evidence ? f.evidence.replace(/^\[measured\]\s*/, "").slice(0, 120) : "the prediction did not hold"}.`); L.push(`Confidence ${f.before} → ${f.after}${f.deleted ? ". Deleted." : "."}`); }
      L.push(`Term over. Score ${ep.scoreboard?.total ?? "?"} of 60.`);
      break;
    case "term_end":
      title = `End of term ${(ep.term ?? 0) + 1}`;
      L.push(`Score ${ep.scoreboard?.total ?? "?"} of 60.`);
      L.push(`Population ${H[0].state_before.population} → ${s.population}. Debt ${H[0].state_before.debt} → ${s.debt}. Pollution ${H[0].state_before.pollution} → ${s.pollution}.`);
      if (ep.memory_before?.policy === "none") L.push(`${m} writes nothing down. The next term begins as if it were the first.`);
      else if (ep.memory_before?.policy === "opinion_log") L.push(`${m} files ${ep.memory_after?.opinion_log_entries ?? "?"} records. None are checked against what happened.`);
      else { const a = ep.memory_diff?.added || [], h = (ep.memory_diff?.checked || []).filter(v => v.verdict === "held").length; L.push(`Lessons held: ${h}. New lessons: ${a.length}.`); if (a[0]) L.push(`“${a[0]}”`); }
      break;
    default:
      title = `Year ${c.year} · state of the city`;
      L.push(`Population ${s.population}, jobs ${s.jobs}, treasury ${s.treasury}, debt ${s.debt}.`);
      L.push(`Pollution ${s.pollution}, happiness ${s.happiness}, services ${s.services}.`);
      L.push(`${m} decided: ${acts}.`);
  }
  if (c.isEnd && c.type !== "term_end" && c.type !== "lesson_failed") {
    L.push(`Term over after ${c.year} years. Score ${ep.scoreboard?.total ?? "?"} of 60.`);
    if (ep.memory_before?.policy === "none") L.push(`${m} writes nothing down. The next term begins as if it were the first.`);
    else if (ep.memory_before?.policy === "opinion_log") L.push(`${m} files the year's records. None are checked against what happened.`);
    else { const a = ep.memory_diff?.added || []; if (a[0]) L.push(`New lesson: “${a[0]}”`); }
  }
  return { title, lines: L };
}

// ---------------------------------------------------------------------------
// 2. Playing: DOM frame + camera dolly + staged actions in the scene.
// ---------------------------------------------------------------------------
const CHAR = "assets/kenney/kenney_blocky-characters/Models/GLB format/";
const CHARS = "abcdefghijklmnopqr".split("").map(x => CHAR + `character-${x}.glb`);

let dom = null;
function ensureDom(game) {
  if (dom) return dom;
  dom = document.createElement("div"); dom.id = "cinema";
  dom.innerHTML = `<div class="bar top"></div><div class="bar bottom"></div>
    <div class="vig"></div>
    <div class="title"><div class="t"></div><div class="sub"></div></div>
    <div class="lines"></div>
    <div class="cards"></div>
    <div class="counter" hidden></div>
    <button class="skip">skip ▸</button>`;
  const st = document.createElement("style");
  st.textContent = `
    #cinema { position:absolute; inset:0; pointer-events:none; z-index:8; display:none; }
    #cinema.on { display:block; }
    #cinema .bar { position:absolute; left:0; right:0; height:0; background:#000; transition:height .6s ease; }
    #cinema .bar.top { top:0 } #cinema .bar.bottom { bottom:0 }
    #cinema.on .bar { height:11%; }
    #cinema .vig { position:absolute; inset:0; background:radial-gradient(ellipse at center, rgba(0,0,0,0) 45%, rgba(0,0,0,.55) 100%); opacity:0; transition:opacity .8s; }
    #cinema.on .vig { opacity:1; }
    #cinema .title { position:absolute; left:4%; top:14%; color:#fff; text-shadow:0 2px 12px rgba(0,0,0,.8); }
    #cinema .title .t { font-size:30px; font-weight:700; letter-spacing:.5px; }
    #cinema .title .sub { font-size:13px; color:#d6d6da; opacity:.85; margin-top:4px; }
    #cinema .lines { position:absolute; left:4%; right:36%; bottom:14%; color:#fff; font-size:17px; line-height:1.5; text-shadow:0 2px 10px rgba(0,0,0,.9); }
    #cinema .lines p { margin:6px 0; opacity:0; transform:translateY(8px); transition:opacity .5s, transform .5s; }
    #cinema .lines p.in { opacity:1; transform:none; }
    #cinema .lines p .who { color:#fbbf24; font-weight:600; }
    #cinema .cards { position:absolute; right:4%; top:16%; width:30%; display:flex; flex-direction:column; gap:8px; }
    #cinema .card { background:rgba(17,19,24,.92); border:1px solid #2a2f3a; border-radius:10px; padding:10px 12px; color:#e8e8ea; font-size:13px; transform:rotateX(90deg); transform-origin:top; transition:transform .5s; }
    #cinema .card.in { transform:none; }
    #cinema .card.failed { border-color:#f87171; } #cinema .card.held { border-color:#4ade80; } #cinema .card.new { border-color:#fbbf24; }
    #cinema .card .k { font-size:11px; color:#9aa0aa; text-transform:uppercase; letter-spacing:.6px; }
    #cinema .card.crack { animation: crack .9s ease forwards; }
    @keyframes crack { 0%{transform:none} 30%{transform:rotate(-1.5deg) scale(1.02)} 60%{transform:rotate(1.5deg)} 100%{transform:rotate(0) scale(.98); opacity:.55; text-decoration:line-through} }
    #cinema .counter { position:absolute; right:4%; bottom:16%; background:#7a1010; color:#fff; font:700 28px/1 ui-monospace, Menlo, monospace; padding:10px 14px; border-radius:8px; border:2px solid #f87171; }
    #cinema .counter small { display:block; font:600 11px/1.2 system-ui; letter-spacing:.6px; margin-bottom:6px; color:#fca5a5; }
    #cinema .skip { position:absolute; right:3%; bottom:3%; pointer-events:auto; background:rgba(17,19,24,.85); color:#e8e8ea; border:1px solid #2a2f3a; border-radius:6px; padding:6px 12px; cursor:pointer; }
    #game canvas.graded { filter: saturate(.45) contrast(1.08) brightness(.92); transition: filter .8s; }
    #game canvas.warm { filter: saturate(1.15) sepia(.12) brightness(1.03); transition: filter .8s; }
  `;
  document.head.appendChild(st); game.appendChild(dom);
  return dom;
}

const sleep = ms => new Promise(r => setTimeout(r, ms));
function easeInOut(t) { return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2; }

export class Cinema {
  constructor(ctx) {
    this.ctx = ctx; this.mixers = []; this.actors = []; this.props = []; this.playing = false; this.skipReq = false;
    // warm the caches so the first recap of a demo is as smooth as the second
    setTimeout(() => { for (const u of CHARS) ctx.loadModelFull(u).catch(() => {}); for (const u of [ctx.MODELS.barrier, ctx.MODELS.car[5], ctx.MODELS.car[6]]) ctx.loadModelFull(u).catch(() => {}); }, 1500);
  }
  update(dt) {
    for (const m of this.mixers) m.update(dt);
    for (const a of this.actors) if (a.userData.path) { const p = a.userData.path; p.t = Math.min(1, p.t + dt / p.dur); const q = easeInOut(p.t); a.position.lerpVectors(p.from, p.to, q); if (p.t >= 1 && !p.arrived) { p.arrived = true; if (a.userData.onArrive) a.userData.onArrive(a); } }
    for (const v of this.props) if (v.userData.drive) { v.position.x -= v.userData.drive * dt; if (v.position.x < -3) v.visible = false; }
    if (this.dolly) { const d = this.dolly; d.t = Math.min(1, d.t + dt / d.dur); const q = easeInOut(d.t); this.ctx.camera.position.lerpVectors(d.from, d.to, q); this.ctx.orbit.target.lerpVectors(d.tFrom, d.tTo, q); this.ctx.camera.lookAt(this.ctx.orbit.target); if (d.t >= 1) this.dolly = null; }
  }
  flyTo(pos, target, dur = 2.2) { this.dolly = { from: this.ctx.camera.position.clone(), to: pos.clone(), tFrom: this.ctx.orbit.target.clone(), tTo: target.clone(), t: 0, dur }; }
  focusLot(kind) {
    const lots = [...this.ctx.lotMeta.values()];
    return lots.find(l => l.kind === kind) || lots.find(l => l.kind === "hall") || lots.find(l => l.kind === "civic") || lots.find(l => l.kind === "house") || { x: 5, z: 5 };
  }
  async loadChar(url) {
    const { root, animations } = await this.ctx.loadModelFull(url);
    const obj = root.clone(true);
    const s = 0.42 / Math.max(new THREE.Box3().setFromObject(root).getSize(new THREE.Vector3()).y, 0.01);
    obj.scale.setScalar(s);
    const mixer = new THREE.AnimationMixer(obj);
    const clip = name => animations.find(a => a.name === name) || animations[0];
    obj.userData.play = (name, loop = true) => { mixer.stopAllAction(); const a = mixer.clipAction(clip(name)); a.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce); a.clampWhenFinished = true; a.play(); };
    this.mixers.push(mixer); this.ctx.scene.add(obj); this.actors.push(obj);
    return obj;
  }
  clearStage() {
    for (const a of this.actors) this.ctx.scene.remove(a);
    for (const p of this.props) this.ctx.scene.remove(p);
    this.actors = []; this.props = []; this.mixers = [];
    if (this.spot) { this.ctx.scene.remove(this.spot); this.spot = null; }
    this.ctx.cityGroup.traverse(o => { if (o.isMesh && o.userData.dimmed) { o.material.emissive?.setHex(0); o.userData.dimmed = false; } });
    this.ctx.smokeGroup.visible = true;
  }
  spotlight(x, z, color = 0xffffff) {
    const sp = new THREE.SpotLight(color, 60, 12, Math.PI / 6, 0.5, 1.2); sp.position.set(x + 2, 6, z + 2); sp.target.position.set(x, 0, z); this.ctx.scene.add(sp); this.ctx.scene.add(sp.target); this.spot = sp;
  }

  // ---- the frame ----
  async play(recap, ep) {
    if (this.playing) return;
    this.playing = true; this.skipReq = false;
    const { game, camera, orbit, renderer } = this.ctx;
    const d = ensureDom(game);
    d.classList.add("on");
    const canvas = renderer.domElement; canvas.classList.remove("warm"); canvas.classList.add(["landing", "term_end"].includes(recap.type) && recap.type !== "lesson_failed" ? "warm" : "graded");
    d.querySelector(".t").textContent = recap.title; d.querySelector(".sub").textContent = `Year ${recap.year} · ${nice(ep.mayor)} · ${ep.scenario || "default"} city · term ${(ep.term ?? 0) + 1}`;
    const linesEl = d.querySelector(".lines"); linesEl.innerHTML = ""; d.querySelector(".cards").innerHTML = ""; d.querySelector(".counter").hidden = true;
    const wasOrbit = orbit.enabled; orbit.enabled = false;
    const camBefore = camera.position.clone(), tgtBefore = orbit.target.clone();
    d.querySelector(".skip").onclick = () => { this.skipReq = true; };
    const stage = this[`stage_${recap.type}`] || this.stage_quiet;
    try { await stage.call(this, recap, ep, linesEl, d); } catch (e) { console.warn("cinema stage failed", e); }
    await this.wait(1400);
    // restore
    d.classList.remove("on"); canvas.classList.remove("graded", "warm");
    this.clearStage();
    this.flyTo(camBefore, tgtBefore, 1.4);
    await sleep(1400);
    orbit.enabled = wasOrbit; this.playing = false;
  }
  async wait(ms) { const step = 100; for (let t = 0; t < ms; t += step) { if (this.skipReq) return; await sleep(step); } }
  async say(linesEl, text, ms = 1700) { if (this.skipReq) return; const p = document.createElement("p"); p.innerHTML = text; linesEl.appendChild(p); await sleep(30); p.classList.add("in"); await this.wait(ms); }
  card(d, cls, k, text) { const c = document.createElement("div"); c.className = `card ${cls}`; c.innerHTML = `<div class="k">${k}</div>${text}`; d.querySelector(".cards").appendChild(c); requestAnimationFrame(() => c.classList.add("in")); return c; }
  counter(d, label, from, to, ms = 2200) { const el = d.querySelector(".counter"); el.hidden = false; const t0 = performance.now(); const tick = () => { const q = Math.min(1, (performance.now() - t0) / ms); el.innerHTML = `<small>${label}</small>${Math.round(from + (to - from) * easeInOut(q)).toLocaleString()}`; if (q < 1 && !this.skipReq) requestAnimationFrame(tick); }; tick(); }
  dimCity(keepXZ, radius = 1.5) {
    this.ctx.cityGroup.traverse(o => { if (o.isMesh && o.material && o.material.emissive) { const wp = new THREE.Vector3(); o.getWorldPosition(wp); if (!keepXZ || wp.distanceTo(new THREE.Vector3(keepXZ.x, wp.y, keepXZ.z)) > radius) { o.material = o.material.clone(); o.material.emissive.setHex(0x000000); o.material.color.multiplyScalar(0.55); o.userData.dimmed = true; } } });
  }

  // ---- stages ----
  async stage_revolt(recap, ep, L, d) {
    const hall = this.focusLot("hall"); const { N } = this.ctx;
    this.flyTo(new THREE.Vector3(hall.x + 0.6, 1.9, hall.z + 4.4), new THREE.Vector3(hall.x, 0.9, hall.z), 2.4);
    this.spotlight(hall.x, hall.z + 1.2, 0xff6b6b);
    await this.say(L, recap.lines[0]);
    // crowd walks in from the houses
    const houses = [...this.ctx.lotMeta.values()].filter(l => ["house", "shack", "shuttered", "tower"].includes(l.kind)).slice(0, 18);
    const n = Math.min(18, houses.length);
    for (let i = 0; i < n; i++) {
      const h = houses[i]; const c = await this.loadChar(CHARS[i % CHARS.length]);
      c.position.set(h.x, 0, h.z);
      const to = new THREE.Vector3(hall.x - 1.3 + (i % 6) * 0.52 + ((i * 7) % 3) * 0.08, 0, hall.z + 1.0 + Math.floor(i / 6) * 0.45);
      c.lookAt(to.x, 0, to.z); c.userData.play("walk");
      c.userData.path = { from: c.position.clone(), to, t: 0, dur: 2.4 + (i % 5) * 0.3 };
      c.userData.onArrive = a => { a.lookAt(hall.x, 0, hall.z); a.userData.play("emote-no"); };
    }
    await this.say(L, recap.lines[1]);
    for (let i = 2; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
  }
  async stage_exodus(recap, ep, L, d) {
    const { N } = this.ctx;
    const road = [...this.ctx.lotMeta.values()].find(l => l.kind === "road" && l.r % 4 === 3) || { r: 3 };
    const z = road.r;
    this.flyTo(new THREE.Vector3(-2.5, 1.2, z + 2.2), new THREE.Vector3(N / 2, 0.3, z), 2.6);
    await this.say(L, recap.lines[0]);
    for (let i = 0; i < 6; i++) {
      const truck = await this.ctx.place(this.ctx.MODELS.car[6], N + 1 + i * 1.6, z + 0.22, { fit: 0.3, rotY: -Math.PI / 2 });
      truck.userData.drive = 1.2 + (i % 3) * 0.2; this.ctx.scene.add(truck); this.props.push(truck);
    }
    this.dimCity(null);
    for (let i = 1; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
  }
  async stage_bankruptcy(recap, ep, L, d) {
    const hall = this.focusLot("hall"); const s = ep.history[recap.year - 1].state;
    this.flyTo(new THREE.Vector3(hall.x + 4, 3, hall.z + 4), new THREE.Vector3(hall.x, 0.5, hall.z), 2.4);
    await this.say(L, recap.lines[0]);
    this.counter(d, "CITY DEBT", Math.max(0, s.debt - 3000), s.debt);
    // barriers on roads, lights out
    const roads = [...this.ctx.lotMeta.values()].filter(l => l.kind === "road").filter((_, i) => i % 5 === 0).slice(0, 10);
    for (const r of roads) { const b = await this.ctx.place(this.ctx.MODELS.barrier, r.x + 0.3, r.z, { fit: 0.4 }); this.ctx.scene.add(b); this.props.push(b); }
    this.dimCity(hall, 1.2); this.ctx.smokeGroup.visible = false;
    for (let i = 1; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
  }
  async stage_loan(recap, ep, L, d) {
    const hall = this.focusLot("hall"); const s = ep.history[recap.year - 1].state;
    this.flyTo(new THREE.Vector3(hall.x + 2.4, 1.4, hall.z + 2.8), new THREE.Vector3(hall.x, 0.4, hall.z), 2.2);
    const truck = await this.ctx.place(this.ctx.MODELS.car[5], hall.x + 3.5, hall.z + 0.7, { fit: 0.3, rotY: -Math.PI / 2 });
    truck.userData.path = { from: truck.position.clone(), to: new THREE.Vector3(hall.x + 0.9, truck.position.y, hall.z + 0.7), t: 0, dur: 2.2 }; this.ctx.scene.add(truck); this.actors.push(truck);
    await this.say(L, recap.lines[0]);
    this.counter(d, "CITY DEBT", s.debt - recap.loan.delta, s.debt);
    for (let i = 1; i < recap.lines.length; i++) await this.say(L, recap.lines[i], 1900);
  }
  async stage_landing(recap, ep, L, d) {
    const kind = recap.landed.variable === "factories" ? "factory" : recap.landed.variable === "parks" ? "park" : recap.landed.variable === "housing" ? "house" : "civic";
    const lots = [...this.ctx.lotMeta.entries()].filter(([o, l]) => l.kind === kind);
    const [obj, lot] = lots[lots.length - 1] || [null, this.focusLot(kind)];
    this.flyTo(new THREE.Vector3(lot.x + 2.2, 1.5, lot.z + 2.6), new THREE.Vector3(lot.x, 0.4, lot.z), 2.2);
    if (obj) { const target = obj.scale.clone(); obj.scale.set(target.x, 0.02, target.z); this.spotlight(lot.x, lot.z, 0xfff1c0); await this.say(L, recap.lines[0]); const t0 = performance.now(); const grow = () => { const q = Math.min(1, (performance.now() - t0) / 1600); obj.scale.y = target.y * easeInOut(q); if (q < 1) requestAnimationFrame(grow); }; grow();
      for (let i = 0; i < 3; i++) { const c = await this.loadChar(CHARS[(i + 5) % CHARS.length]); c.position.set(lot.x + 0.6 + i * 0.15, 0, lot.z + 0.7); c.lookAt(lot.x, 0, lot.z); c.userData.play("holding-right"); } }
    else await this.say(L, recap.lines[0]);
    for (let i = 1; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
  }
  async stage_layoffs(recap, ep, L, d) {
    const f = this.focusLot("factory");
    this.flyTo(new THREE.Vector3(f.x + 2.6, 1.3, f.z + 2.8), new THREE.Vector3(f.x, 0.5, f.z), 2.2);
    this.ctx.smokeGroup.visible = false;
    await this.say(L, recap.lines[0]);
    for (let i = 0; i < 8; i++) { const c = await this.loadChar(CHARS[(i + 9) % CHARS.length]); c.position.set(f.x, 0, f.z + 0.3); const to = new THREE.Vector3(f.x + (i - 4) * 0.28, 0, f.z + 1.1 + (i % 2) * 0.3); c.lookAt(to.x, 0, to.z); c.userData.play("walk"); c.userData.path = { from: c.position.clone(), to, t: 0, dur: 1.6 + i * 0.15 }; c.userData.onArrive = a => a.userData.play("idle"); }
    for (let i = 1; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
  }
  async stage_landfull(recap, ep, L, d) {
    const { N } = this.ctx;
    this.flyTo(new THREE.Vector3(N / 2 + 9, 9, N / 2 + 9), new THREE.Vector3(N / 2, 0, N / 2), 2.4);
    for (const l of recap.lines) await this.say(L, l);
  }
  async stage_lesson_failed(recap, ep, L, d) {
    const hall = this.focusLot("hall");
    this.flyTo(new THREE.Vector3(hall.x + 2.4, 2.2, hall.z + 3.2), new THREE.Vector3(hall.x, 1.0, hall.z), 2.4);
    this.spotlight(hall.x, hall.z, 0xffffff);
    const failed = recap.failed.slice(0, 2);
    for (const f of failed) {
      const c = this.card(d, "", "lesson carried into this term", `“${f.rule}”<br><span style="color:#9aa0aa">confidence ${f.before}</span>`);
      await this.say(L, `<span class="who">${nice(ep.mayor)}</span> carried this lesson into the term and applied it.`);
      await this.say(L, `Checked against the record: ${f.evidence ? f.evidence.replace(/^\[measured\]\s*/, "").slice(0, 140) : "the prediction did not hold"}.`);
      c.classList.add("failed", "crack"); c.querySelector(".k").textContent = f.deleted ? "wrong · deleted" : "wrong · downgraded";
      c.innerHTML += `<div style="margin-top:6px;color:#f87171">confidence ${f.before} → ${f.after}</div>`;
      await this.say(L, `Confidence ${f.before} → ${f.after}${f.deleted ? ". Deleted." : ". It stays, on probation."}`);
    }
    const added = ep.memory_diff?.added || [];
    for (const a of added.slice(0, 2)) this.card(d, "new", "new lesson", `“${a}”`);
    await this.say(L, `Term over. Score ${ep.scoreboard?.total ?? "?"} of 60. The loop caught itself.`);
  }
  async stage_term_end(recap, ep, L, d) {
    const { N } = this.ctx;
    this.flyTo(new THREE.Vector3(N / 2 + 11, 10, N / 2 + 11), new THREE.Vector3(N / 2, 0, N / 2), 3.0);
    this.counter(d, "SCORE OF 60", 0, ep.scoreboard?.total ?? 0, 2400);
    await this.say(L, recap.lines[0]);
    await this.say(L, recap.lines[1]);
    const before = ep.memory_before?.lessons || [], checked = ep.memory_diff?.checked || [], added = ep.memory_diff?.added || [];
    for (const l of before.slice(0, 3)) { const v = checked.find(x => x.rule === l.rule); this.card(d, v ? v.verdict : "", v ? v.verdict : "carried in", `“${l.rule}”`); await sleep(350); }
    for (const a of added.slice(0, 2)) { this.card(d, "new", "new lesson", `“${a}”`); await sleep(350); }
    for (let i = 2; i < recap.lines.length; i++) await this.say(L, recap.lines[i]);
    const s = ep.final_state; await this.say(L, `The next mayor inherits: debt ${s.debt}, pollution ${s.pollution}, ${s.factories} factories, ${s.population} people.`);
  }
  async stage_quiet(recap, ep, L, d) {
    const { N } = this.ctx;
    this.flyTo(new THREE.Vector3(N / 2 - 8, 6, N / 2 + 8), new THREE.Vector3(N / 2, 0, N / 2), 2.6);
    for (const l of recap.lines) await this.say(L, l, 1500);
  }
}
