// Narrator ("the Chronicler") and Freeze-and-Ask.
//
// The chronicler stops the clock at the moments that matter and says, from the cause-tagged
// events, what just happened and who decided it. Text is generated by template from the
// record, so it never invents a fact. Click Continue, or let it auto-advance.
//
// Freeze-and-ask opens a panel where you pick someone in the city and ask them anything.
// Answers come from a local server (ask_server.py) so no API key ever sits in this page.

(function () {
  const ASK_URL = "http://localhost:8766/ask";
  const card = document.createElement("div");
  card.id = "chronicler";
  card.innerHTML = `
    <div class="ch-inner">
      <div class="ch-head"><span class="ch-face">📜</span><div><div class="ch-title"></div><div class="ch-sub"></div></div>
        <label class="ch-auto"><input type="checkbox" id="ch-autopause" checked> pause at moments</label></div>
      <div class="ch-body"></div>
      <div class="ch-actions">
        <button class="primary" id="ch-continue">Continue ▶</button>
        <button id="ch-ask">Ask someone…</button>
      </div>
      <div class="ch-askpanel" hidden>
        <div class="ch-people"></div>
        <div class="ch-q"><input id="ch-question" placeholder="Ask anything… how are things? what did the mayor do? how's your kid?" />
          <button id="ch-send" class="primary">Ask</button></div>
        <div class="ch-answer" hidden></div>
      </div>
    </div>`;
  document.body.appendChild(card);
  const style = document.createElement("style");
  style.textContent = `
    #chronicler { position:fixed; inset:0; background:rgba(0,0,0,.55); display:none; align-items:center; justify-content:center; z-index:20; }
    #chronicler.open { display:flex; }
    .ch-inner { width:min(760px, 92vw); background:#171a21; border:1px solid #2a2f3a; border-radius:14px; padding:18px 20px; color:#e8e8ea; box-shadow:0 20px 60px rgba(0,0,0,.6); }
    .ch-head { display:flex; gap:12px; align-items:center; }
    .ch-face { font-size:34px; }
    .ch-title { font-weight:600; font-size:16px; }
    .ch-sub { color:#9aa0aa; font-size:12px; }
    .ch-auto { margin-left:auto; color:#9aa0aa; font-size:12px; display:flex; gap:6px; align-items:center; }
    .ch-body { margin:14px 0; font-size:15px; line-height:1.55; }
    .ch-body p { margin:6px 0; }
    .ch-body .who { color:#fbbf24; font-weight:600; }
    .ch-actions { display:flex; gap:10px; }
    .ch-askpanel { margin-top:14px; border-top:1px solid #2a2f3a; padding-top:12px; }
    .ch-people { display:flex; gap:8px; flex-wrap:wrap; margin-bottom:10px; }
    .ch-person { background:#0f1115; border:1px solid #2a2f3a; border-radius:10px; padding:8px 10px; cursor:pointer; display:flex; gap:8px; align-items:center; font-size:13px; }
    .ch-person.sel { border-color:#2563eb; background:#1b2436; }
    .ch-person .pf { font-size:22px; }
    .ch-q { display:flex; gap:8px; }
    .ch-q input { flex:1; background:#0f1115; color:#e8e8ea; border:1px solid #2a2f3a; border-radius:8px; padding:8px 10px; font-size:14px; }
    .ch-answer { margin-top:12px; background:#0f1115; border-radius:10px; padding:12px 14px; font-size:14px; line-height:1.5; }
    .ch-answer .who { color:#4ade80; font-weight:600; }
  `;
  document.head.appendChild(style);

  const PEOPLE = [
    { id: "worker", face: "👩‍🏭", name: "Ama, factory worker", blurb: "single parent, ten-year-old" },
    { id: "mayor", face: "🎩", name: "The Mayor", blurb: "will explain himself" },
    { id: "industrialist", face: "🏭", name: "Bram, industrialist", blurb: "owns the factories" },
    { id: "environmentalist", face: "🌿", name: "Dr. Nadia, environmentalist", blurb: "lives downwind, counts smog days" },
    { id: "shopkeeper", face: "🛒", name: "Rosa, shopkeeper", blurb: "corner shop by the main road" },
  ];
  let selected = "worker";
  const peopleEl = card.querySelector(".ch-people");
  peopleEl.innerHTML = PEOPLE.map(p => `<div class="ch-person ${p.id === selected ? "sel" : ""}" data-id="${p.id}"><span class="pf">${p.face}</span><div><div>${p.name}</div><div style="color:#9aa0aa;font-size:11px">${p.blurb}</div></div></div>`).join("");
  peopleEl.addEventListener("click", e => {
    const el = e.target.closest(".ch-person"); if (!el) return;
    selected = el.dataset.id;
    peopleEl.querySelectorAll(".ch-person").forEach(x => x.classList.toggle("sel", x.dataset.id === selected));
  });

  // ---------- moments: what deserves a pause ----------
  const NAMES = window.MAYOR_NAMES || {};
  const nice = m => NAMES[m] || m;
  const LEVER_WORDS = { build_factory: "a factory", build_park: "a park", build_housing: "new housing", fund_transit: "a transit line",
    fund_services: "services funding", subsidize_business: "business subsidies", borrow: "a loan", set_tax: "a tax change", demolish: "a demolition", buy_land: "a land purchase" };

  function momentsFor(ep, year) {
    const rec = ep.history[year - 1]; if (!rec) return [];
    const prev = year >= 2 ? ep.history[year - 2].state : ep.history[0].state_before;
    const s = rec.state, out = [];
    const mayor = nice(ep.mayor);
    if (year === 1 && ep.inherited) {
      const b = ep.history[0].state_before;
      out.push(`<span class="who">${mayor}</span> begins a new term in the city ${mayor === "Caesar" ? "he" : "it"} left behind: debt ${b.debt}, ${b.factories} factories, pollution ${b.pollution}, happiness ${b.happiness}. Nothing was reset.`);
    }
    // delayed consequences landing
    for (const e of rec.events) {
      if (e.cause_action === "economy" || e.cause_year >= year) continue;
      if (["factories", "parks", "housing", "transit"].includes(e.variable) || (e.variable === "jobs" && e.cause_action === "subsidize_business")) {
        out.push(`${LEVER_WORDS[e.cause_action] || e.cause_action} ordered in <b>year ${e.cause_year}</b> lands now: ${e.variable} ${e.delta > 0 ? "+" : ""}${Math.round(e.delta)}${e.note ? ` (${e.note})` : ""}.`);
      }
    }
    // borrowing
    const loan = rec.events.find(e => e.cause_action === "borrow" && e.variable === "debt" && e.cause_year === year);
    if (loan) out.push(`<span class="who">${mayor}</span> borrows ${Math.round(loan.delta)}. Debt is now ${s.debt}; interest of about ${Math.round(s.debt * 0.08)} a year follows, forever.`);
    // big swings
    const dh = s.happiness - prev.happiness, dp = (s.population - prev.population) / Math.max(prev.population, 1);
    if (dh <= -6) out.push(`Happiness falls ${Math.abs(dh).toFixed(0)} points to ${s.happiness}. People are noticing.`);
    if (dh >= 6) out.push(`Happiness rises ${dh.toFixed(0)} points to ${s.happiness}.`);
    if (dp <= -0.06) out.push(`${Math.round(-dp * 100)}% of the population leaves this year (${prev.population} → ${s.population}).`);
    if (dp >= 0.08) out.push(`People are moving in: ${prev.population} → ${s.population}.`);
    if (prev.treasury >= 0 && s.treasury < 0) out.push(`The treasury goes negative: ${s.treasury}.`);
    if (s.unemployment >= 0.2 && (prev.unemployment || 0) < 0.2) out.push(`Unemployment crosses 20%.`);
    // refused builds (land)
    const refused = rec.ignored.filter(i => /lots/.test(i.why));
    if (refused.length) out.push(`A build was refused: ${refused[0].why}. The city is out of land.`);
    // ending
    if (rec.ended && rec.ended !== "horizon") out.push(`<b>The term ends early: ${rec.ended.toUpperCase()}.</b>`);
    if (rec.ended === "horizon") {
      const sb = ep.scoreboard || {};
      out.push(`Term over. Score ${sb.total ?? "?"} of 60.`);
      const failed = (ep.memory_diff?.checked || []).filter(v => v.verdict === "failed");
      for (const f of failed) out.push(`<span class="who">${mayor}</span> reviews a lesson and finds it wrong: “${f.rule}” (confidence ${f.before} → ${f.after}${f.deleted ? ", deleted" : ""}).`);
      const added = ep.memory_diff?.added || [];
      if (added.length) out.push(`New lessons written: ${added.slice(0, 2).map(a => `“${a}”`).join(" · ")}${added.length > 2 ? " …" : ""}`);
      if (ep.memory_before?.policy === "none") out.push(`<span class="who">${mayor}</span> writes nothing down. Next term begins as if it were the first.`);
    }
    return out;
  }

  // ---------- open / close ----------
  let ctx = null; // {ep, year}
  function open(ep, year, lines) {
    ctx = { ep, year };
    card.querySelector(".ch-title").textContent = `Year ${year} · ${nice(ep.mayor)} · ${ep.scenario || "default"} city`;
    card.querySelector(".ch-sub").textContent = `term ${(ep.term ?? 0) + 1}${ep.inherited ? " (inherited)" : ""} · the chronicler`;
    card.querySelector(".ch-body").innerHTML = lines.map(l => `<p>${l}</p>`).join("");
    card.querySelector(".ch-askpanel").hidden = true;
    card.querySelector(".ch-answer").hidden = true;
    card.classList.add("open");
  }
  function close() { card.classList.remove("open"); }
  card.querySelector("#ch-continue").onclick = () => { close(); if (window.__resumePlay) window.__resumePlay(); };
  card.querySelector("#ch-ask").onclick = () => { card.querySelector(".ch-askpanel").hidden = false; card.querySelector("#ch-question").focus(); };
  card.addEventListener("click", e => { if (e.target === card) close(); });

  async function send() {
    if (!ctx) return;
    const q = card.querySelector("#ch-question").value.trim() || "How are things going?";
    const { ep, year } = ctx;
    const rec = ep.history[Math.max(0, Math.min(year, ep.history.length) - 1)];
    const ans = card.querySelector(".ch-answer");
    const who = PEOPLE.find(p => p.id === selected);
    ans.hidden = false; ans.innerHTML = `<span class="who">${who.face} ${who.name}</span> is thinking…`;
    try {
      const r = await fetch(ASK_URL, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({
        character: selected, question: q, mayor: ep.mayor, state: rec ? rec.state : ep.final_state,
        recent_events: rec ? rec.events : [], reasoning: rec ? rec.reasoning : "", year, term: ep.term, scenario: ep.scenario,
        prev_state: rec ? rec.state_before : null, ended: (rec && year >= ep.years && ep.ended !== "horizon") ? ep.ended : null,
        lessons: (ep.memory_before?.lessons || []).map(l => l.rule),
      }) });
      const j = await r.json();
      ans.innerHTML = `<span class="who">${who.face} ${who.name}</span><br>${(j.answer || "(no answer)").replace(/</g, "&lt;")}`;
    } catch (e) {
      ans.innerHTML = `<span class="who">${who.face} ${who.name}</span><br>(the ask server isn't running: <code>python ask_server.py</code>)`;
    }
  }
  card.querySelector("#ch-send").onclick = send;
  card.querySelector("#ch-question").addEventListener("keydown", e => { if (e.key === "Enter") send(); });

  // ---------- hooks used by index.html ----------
  // Called after each rendered year with the visible episodes. Returns true if it paused.
  window.chroniclerCheck = function (view, year) {
    if (!document.getElementById("ch-autopause").checked) return false;
    for (const ep of view) {
      const lines = momentsFor(ep, year);
      if (lines.length) { open(ep, year, lines); return true; }
    }
    return false;
  };
  // Manual freeze: summarize this year for the first city, or the one clicked.
  window.chroniclerOpen = function (ep, year) {
    const lines = momentsFor(ep, year);
    open(ep, year, lines.length ? lines : [`A quiet year in ${nice(ep.mayor)}'s city. Population ${ep.history[year - 1]?.state.population ?? "?"}, happiness ${ep.history[year - 1]?.state.happiness ?? "?"}.`]);
  };
})();
